### ISSUE TITLE
RL Deepracer Notebook FileNotFoundError

### ISSUE THREAD

**Issue by ngluna** [awslabs/amazon-sagemaker-examples#1517]
In: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/deepracer_rl.ipynb

Notebook fails when retrieving: training_metrics.json
`FileNotFoundError: S3 object s3://.../training_metrics.json never appeared after 1200 seconds`

Occurs when you run:
`training_metrics_file = "training_metrics.json" `
`training_metrics_path = "{}/{}".format(s3_prefix, training_metrics_file)`
`wait_for_s3_object(s3_bucket, training_metrics_path, tmp_dir)`

To reproduce error:

Launch SM Notebook instance
Clone https://github.com/awslabs/amazon-sagemaker-examples.git
Open https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/deepracer_rl.ipynb
Click "Cell" -> "Run All"

**Comment by yunzhe-tao** [comment]
Resolved in #1557, merged to main. Thanks!

**Comment by ngluna** [comment]
Thanks for looking into this. 

I pulled in the latest commits, but I am still getting a 

`FileNotFoundError: S3 object s3://sagemaker-us-west-2-xxxxxxxxxxxx/deepracer-notebook-sagemaker-200924-182628/training_metrics.json never appeared after 1200 seconds`

**Comment by yunzhe-tao** [comment]
@ngluna I can't reproduce the error this time. Maybe you can clean the docker images and try it again.

**Comment by varun1295** [comment]
I am facing a similar issue, but for evalution_metrics.json file. @ngluna have you found the  solution?
